### ISSUE TITLE
Please review branch feature/fixing-timelines

### ISSUE THREAD

**Issue by phillipadsmith** [TheTyee/design-article.thetyee.ca#359]
Howdy @alexgreen @MrBryan --

I've just pushed a new branch based off of the current `develop` branch here:
https://github.com/TheTyee/design-article.thetyee.ca/tree/feature/fixing-timelines

There's a chance this branch may also resolve the jQuery conflicts with Wufoo. You'll see that I've downgraded jQuery from 2.x to the latest on the 1.x branch, which resolved the problems that were encountered with the timeline code and jQuery.validate function.

Once you've got this branch checked out and Jekyll running, you can visit /timeline.html and you'll see the timeline loading from a Google Sheet, per this article: http://preview.thetyee.ca/News/2014/07/14/Sanctuary-City-Timeline/

@alexgreen Specifically, I'd like you to have a look to see if there's something we can do to better present vertical timelines like these. Perhaps we can widen the main column / loose the sidebar for these specific stories? 

@MrBryan If possible, I'd like you to double-check that the existing jQuery-dependant functionality is working properly with this version of jQuery. I did a review and didn't see any obvious issues. We should make a list of what that functionality is and I can add that to the test suite to catch problems with future updates.

Thanks both. 

Phillip.

**Comment by alexgreen** [comment]
I get this error when I compile the branch:

```
 Liquid Exception: Included file '_includes/developer-buy-button.html' not found in bower_components/isotope/_posts/docs/2010-12-01-introduction.md
jekyll 2.5.3 | Error:  Included file '_includes/developer-buy-button.html' not found

```

**Comment by phillipadsmith** [comment]
Does your config.yml look like this:

```
# Project settings - General
version: 0.0.1
title: "The Tyee Article Page"
description: ""
baseurl: ""
url: "http://thetyee.github.io/design-article.thetyee.ca/"
logo: 'tyee_logo.png'

# Project settings - Analytics
analytics:
    ga_tracking_id: 'UA-12345-5'

# Project settings - Meta
author: "The Tyee"
robots: "index, follow"
revisit: "1 day"
copyright: "&copy; The Tyee 2015"

# Project settings - Assets
asset_paths:
 # jekyll-assets pipeline
  # Pathname of the destination of generated (bundled) assets relative
  # to the destination of the root.
  dirname: assets
  # Base URL of assets paths.
  baseurl: /assets/
  sources:
    - ui/js
    - ui/img
    - ui/css

# Project settings - URLs
urls:
    display: ''
    privacy: ''
    credits: ''
    credits: ''

# Project settings - Social
social:
    facebook:
        fb_admins:
            - 12345
        og_url:
        og_image:
        og_sitename:
    twitter:
    gplus:

# Jekyll build settings
markdown: kramdown
permalink: pretty
exclude:
  - README.md
  - bower.json
  - package.json
  - node_modules
  - Gruntfile.js
  - gemfile
  - Gemfile.lock
  - bower_components/isotope/index.html
  - bower_components/isotope/_posts/
  - bower_components/isotope/_includes/
  - bower_components/isotope/_layouts/
```

Note the four lines at the end.

And are you running Jekyll with both configs like so:

```
bundle exec jekyll serve -w --config _config.yml,_config.local.yml
```

If not, you'll not get those exclusions in the new config.yml
